### ISSUE TITLE
[Feature Request] Prevent bulb icon from becoming transparent when scrolling down

### ISSUE THREAD

**Issue by rp1231** [rgomezjnr/Smart-Bulb-Control#1]
Hi,

I find that I lose the icon when the icon is in the lower brightness range as it becomes too transparent.
Would it be possible to have a brightness number displayed, or have the bulb become gray instead of transparent?

Thanks

**Comment by rgomezjnr** [comment]
You can modify the script by right-clicking the Rainmeter icon in the system tray, then select Smart Bulb Control -> Edit Skin.

I  just tried increasing the BrightnessMin variable but it doesn't seem to work. The script portion that changes the icon transparency doesn't work that well to be honest since I believe the Brightness variable doesn't update properly. This portion of the script can certainly be improved.

You can try making changes like the following which will change the icon color to gray if the Brightness variable is less than 75:

BrightnessMin=75

![image](https://user-images.githubusercontent.com/55524335/164950466-e19da130-fd0d-44c4-9564-0b652c55bf9c.png)

**Comment by rp1231** [comment]
Thanks,
I'll try it out.

**Comment by rp1231** [comment]
That didn't work for me properly.
But I was able to make it change from black to white making the following changes.
![notepad++_HuSl4fUSpM](https://user-images.githubusercontent.com/47380919/164979101-3bb43e6e-11d2-4cfa-9596-34436a60f79c.png)

This solution works well enough for me,
So I'll be closing this for now.

Thanks
